CREATE TABLE IF NOT EXISTS dolphin_question
(
    id         BIGSERIAL PRIMARY KEY,
    question VARCHAR(1000) NOT NULL UNIQUE,
    answer     TEXT         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
