export enum QuestionType {
  MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
  TEXT_INPUT = "TEXT_INPUT",
  MULTIPLE_TEXT_INPUT = "MULTIPLE_TEXT_INPUT",
  NUMERIC_INPUT = "NUMERIC_INPUT",
  SUBTRACTION_TASK = "SUBTRACTION_TASK",
}
