export enum QuizState {
  PATIENT_INFO = 'PATIENT_INFO',
  ORIENTATION_QUESTIONS = 'ORIENTATION_QUESTIONS',
  ORIENTATION_ANSWERS = 'ORIENTATION_ANSWERS',
  SHOW_TEST_LINK = 'SHOW_TEST_LINK',
  QUIZ = 'QUIZ',
  FINISHED = 'FINISHED'
}
