version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: linux/amd64
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/src/app
    command: python app.py
